name: Test Action

on:
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test v1 branch test
        id: test-versioned-branch-good
        uses: patriotsoftware/delete-branch-resources-action@DVO-5572
        with:
            branch-name: v1
            namespace: unknown
            release-names-array: unknown
            stack-name: unknown
            delete-branch-db: false
            aws-access-key-id: unknown
            aws-secret-access-key: unknown

      - name: Test vuln branch test
        id: test-versioned-branch-other
        uses: patriotsoftware/delete-branch-resources-action@DVO-5572
        with:
            branch-name: vuln
            namespace: unknown
            release-names-array: unknown
            stack-name: unknown
            delete-branch-db: false
            aws-access-key-id: unknown
            aws-secret-access-key: unknown

      - name: Print Status
        run: |
          echo output from action '${{ steps.test-versioned-branch-good.outputs.validate-output }}'
          echo output from action '${{ steps.test-versioned-branch-other.outputs.validate-output }}'